version: '3.3'

services:
   mongo:
      image: mongo
      container_name: mongodb-cliente
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: password
      ports:
         - 27017:27017
      volumes:
         - mongo-data:/D/microservice-cliente/bd
volumes:
   mongo-data: